- name: Gerbera Roles
  hosts: all
  become: yes

  vars:
    playbook_path: |-
        {{
            (
                lookup('file', '/proc/self/cmdline')
                    | regex_replace('\u0000',' ')
            ).split()
                | select('match','^.*[.]ya?ml$')
                | list
                | first
        }}
    real_ansible_dir: "{{ (playbook_path + '/..') | realpath | dirname }}"

  vars_files:
    - "{{ real_ansible_dir }}/../config.yml"
    - "{{ real_ansible_dir }}/vars/global.yml"
    - "{{ real_ansible_dir }}/vars/ipa-config.yml"

  pre_tasks:
    - name: "Enable EL repos"
      include_tasks: "{{ real_ansible_dir }}/enable-el-repos.yml"

    - name: "Find group media-editors"
      command: "getent group media-editors"
      register: getent_group_mediaeditors
      changed_when: no
      ignore_errors: true

    - name: Create group media-editors
      ipa_group:
        name: media-editors
        ipa_pass: "{{ ipaadmin_password }}"
      environment:
        http_proxy: ""
        https_proxy: ""
      when: getent_group_mediaeditors.rc == 2

  roles:
    - default-packages
    - minidlna
