- name: "Hostapd roles"
  hosts: all
  become: yes

  vars:
    hostapd_bridge_slave_if: eth1
    playbook_path: |-
        {{
            (
                lookup('file', '/proc/self/cmdline')
                    | regex_replace('\u0000',' ')
            ).split()
                | select('match','^.*[.]ya?ml$')
                | list
                | first
        }}
    real_ansible_dir: "{{ (playbook_path + '/..') | realpath | dirname }}"

  vars_files:
    - "{{ real_ansible_dir }}/../config.yml"
    - "{{ real_ansible_dir }}/vars/global.yml"
    - "{{ real_ansible_dir }}/vars/ipa-config.yml"

  pre_tasks:
    - name: "Enable EPEL"
      dnf:
        name: epel-release
        state: present

    - name: "Install elrepo"
      dnf:
        name: "https://www.elrepo.org/elrepo-release-9.el9.elrepo.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: "Enable repo elrepo-kernel"
      ini_file:
        path: /etc/yum.repos.d/elrepo.repo
        section: elrepo-kernel
        option: enabled
        value: 1

    - name: "Enable copr"
      command:
        cmd: "dnf -y copr enable nieslony/arachne"
        creates: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:nieslony:arachne.repo"

    - name: "Install packages"
      dnf:
        name: usbutils
        state: present

  roles:
    - hostapd
