- name: "Hostapd roles"
  hosts: all
  become: yes

  vars:
    hostapd_bridge_slave_if: eth1

  pre_tasks:
    - name: "Enable EPEL"
      dnf:
        name: epel-release
        state: present

    - name: "Install elrepo"
      dnf:
        name: "https://elrepo.org/linux/kernel/el9/x86_64/RPMS/elrepo-release-9.1-1.el9.elrepo.noarch.rpm"
        state: present
        disable_gpg_check: yes

    - name: "Enable repo elrepo-kernel"
      ini_file:
        path: /etc/yum.repos.d/elrepo.repo
        section: elrepo-kernel
        option: enabled
        value: 1

    - name: "Enable copr"
      command:
        cmd: "dnf -y copr enable nieslony/arachne"
        creates: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:nieslony:arachne.repo"

    - name: "Install packages"
      dnf:
        name: usbutils
        state: present

  roles:
    - hostapd
