- name: Printserver Roles
  hosts: all
  become: yes

  vars:
    playbook_path: |-
        {{
            (
                lookup('file', '/proc/self/cmdline')
                    | regex_replace('\u0000',' ')
            ).split()
                | select('match','^.*[.]ya?ml$')
                | list
                | first
        }}
    real_ansible_dir: "{{ (playbook_path + '/..') | realpath | dirname }}"

  vars_files:
    - "{{ real_ansible_dir }}/../config.yml"
    - "{{ real_ansible_dir }}/vars/global.yml"
    - "{{ real_ansible_dir }}/vars/ipa-config.yml"

  pre_tasks:
    - name: "Enable EL repos"
      include_tasks: "{{ real_ansible_dir }}/enable-el-repos.yml"

    - name: "Find group printer-admins"
      command: "getent group printer-admins"
      register: group_printer_admins
      changed_when: no
      ignore_errors: true

    - name: "Create group printer-admins"
      ipa_group:
        name: printer-admins
        append: true
        user:
            - rossi
        ipa_pass: "{{ ipaadmin_password }}"
      environment:
        http_proxy: ""
        https_proxy: ""
      when: group_printer_admins.rc == 2

  roles:
    - default-packages
    - printserver
