- name: Webserver Roles
  hosts: all
  become: yes

  vars:
    playbook_path: |-
        {{
            (
                lookup('file', '/proc/self/cmdline')
                    | regex_replace('\u0000',' ')
            ).split()
                | select('match','^.*[.]ya?ml$')
                | list
                | first
        }}
    real_ansible_dir: "{{ (playbook_path + '/..') | realpath | dirname }}"

    webserver_vhosts:
      - "{{ ansible_fqdn }}"
      - "www.{{ ansible_domain }}"
      - "www.test.lab"
    webserver_constrained_delegation_targets:
        ipa-ldap-delegation-targets:
            - "ldap/ipa01.linux.lab@LINUX.LAB"
    webserver_constrained_delegation_rule: webserver-delegation-rule
    webserver_lvm_volsize_gb: 2
    webserver_whoami_app_enabled: yes
    webserver_infopipe_enabled: yes
    webserver_constrained_delegation_enabled: yes

    webserver_oidc_enabled: true
    webserver_oidc_url: http://ipa01.linux.lab:8180
    webserver_oidc_admin_user: kc-admin
    webserver_oidc_admin_password: "{{ keycloak.admin_password }}"
    webserver_oidc_realm:  "{{ organization }}"
    webserver_oidc_client_id: "{{ ansible_fqdn }}"
    webserver_oidc_client_secret: Ieshaephahgheej1

  vars_files:
    - "{{ real_ansible_dir }}/../config.yml"
    - "{{ real_ansible_dir }}/vars/global.yml"
    - "{{ real_ansible_dir }}/vars/ipa-config.yml"

  pre_tasks:
    - name: "Enable EL repos"
      include_tasks: "{{ real_ansible_dir }}/enable-el-repos.yml"

  roles:
    - default-packages
    - webserver
