- name: Apply Workstation Roles
  hosts: all
  become: true

  vars:
    trusted_uris: [".linux.lab", ".test.lab"]
    delegation_uris: ["cloud.test.lab"]
    managed_bookmarks:
        - name: "Nextcloud"
          url: "https://cloud.test.lab"
        - name: "Printserver"
          url: "https://printserver.linux.lab:631"
        - name: "IPA Server"
          url: "https://ipa01.linux.lab"
        - name: "gateway"
          url: "http://192.168.120.254"
    skip_repo_backup: true
    commercial_packages: []
    gui_rpm_packages_fedora:
        - sddm
        - dolphin
    print_server: printserver.linux.lab

    file_bookmarks:
        - name: "Music on Fileserver"
          url: "file:///data/music"
          icon: "folder-remote-nfs"
        - name: "Videos on Fileserver"
          url: "file:///data/videos"
          icon: "folder-remote-nfs"
        - name: "Data on fileserver"
          url: "file:///data/data"
          icon: "folder-remote-nfs"

  roles:
    - gui
    - evolution
    - firefox
    - thunderbird
    - thunderbird
    - autofs

  post_tasks:
    - name: "Reboot"
      reboot:
      changed_when: no
