#ipadm_password: "IpaAdminPassword.1"
#ipaadmin_password: "IpaAdminPassword.1"
ipadm_password: "{{ ipa.admin_password }}"
ipaadmin_password: "{{ ipa.admin_password }}"
ipaserver_domain: linux.lab
ipaserver_realm: LINUX.LAB
ipaserver_no_dnssec_validation: no
ipaserver_setup_kra: yes
ipaserver_setup_dns: yes

ipaserver_auto_reverse: no
ipaserver_auto_forwarders: no
ipaserver_no_forwarders: yes
ipaserver_no_host_dns: yes
ipaserver_no_reverse: yes
#ipaserver_reverse_zones:
    #- 192.168.120.0
ipaserver_ip_addresses:
    - 192.168.120.20
ipaclient_mkhomedir: yes
ipaclient_ssh_trust_dns: yes
ipaclient_configure_firefox: yes
ipasssd_enable_dns_updates: yes
ipaservers:
    - ipa01.linux.lab
