- name: Enable PowerTools
  command: "dnf config-manager --set-enabled powertools"
  when:
    - ansible_distribution_file_variety == "RedHat"
    - ansible_distribution_major_version == "8"

- block:
    - name: "Find CRB repo"
      shell: "dnf repolist --enabled | grep -q '^crb '"
      register: find_crb_repo
      changed_when: no
      failed_when: no

    - name: Enable CRB
      command: "dnf config-manager --set-enabled crb"
      when: find_crb_repo.rc != 0
  when:
    - ansible_distribution_file_variety == "RedHat"
    - ansible_distribution_major_version == "9"

- name: Enble EPEL
  dnf:
    name:
      - epel-release
    state: latest
