- name: Gerbera Roles
  hosts: all
  become: yes

  vars:
    repo_whitelist:
        - almalinux-appstream.repo
        - almalinux-baseos.repo
        - almalinux-crb.repo
        - centos.repo
        - epel-cisco-openh264.repo
        - epel-next.repo
        - epel.repo

    exports:
        - { path: /data/music, share: music, automount_key: music }
        - { path: /data/videos, share: videos, automount_key: videos }

  pre_tasks:
    - set_fact:
        playbook_path: "{{ (lookup('file', '/proc/self/cmdline') | regex_replace('\u0000',' ')).split() | select('match','^.*[.]ya?ml$') | list | first }}"

    - set_fact:
        real_playbook_dir: "{{ playbook_path | realpath | dirname }}"

    - include_vars: "{{ real_playbook_dir }}/../config.yml"

    - include_vars: "{{ real_playbook_dir }}/ipa-vars.yml"

    - name: Enable PowerTools
      command: "dnf config-manager --set-enabled powertools"
      when:
        - ansible_distribution_file_variety == "RedHat"
        - ansible_distribution_major_version == "8"

    - name: Enable CRB
      command: "dnf config-manager --set-enabled crb"
      when:
        - ansible_distribution_file_variety == "RedHat"
        - ansible_distribution_major_version == "9"

    - name: Enble EPEL
      dnf:
        name:
          - epel-release
        state: latest

    - name: "Find group media-editors"
      command: "getent group media-editors"
      register: getent_group_mediaeditors
      changed_when: no
      ignore_errors: true

    - name: Create group media-editors
      ipa_group:
        name: media-editors
        ipa_pass: "{{ ipaadmin_password }}"
      environment:
        http_proxy: ""
        https_proxy: ""
      when: getent_group_mediaeditors.rc == 2

  roles:
    - default-packages
    - minidlna
    - fileserver
