- name: Mail Roles
  hosts: all
  become: yes

  vars:
    repo_whitelist:
        - almalinux-appstream.repo
        - almalinux-baseos.repo
        - almalinux-crb.repo
        - centos.repo
        - epel-cisco-openh264.repo
        - epel-next.repo
        - epel.repo

  pre_tasks:
    - name: Enable PowerTools
      command: "dnf config-manager --set-enabled powertools"
      when:
        - ansible_distribution_file_variety == "RedHat"
        - ansible_distribution_major_version == "8"

    - name: Enable CRB
      command: "dnf config-manager --set-enabled crb"
      when:
        - ansible_distribution_file_variety == "RedHat"
        - ansible_distribution_major_version == "9"

    - name: Enble EPEL
      dnf:
        name:
          - epel-release
        state: latest

  roles:
    - default-packages
    - mailserver
