- name: Use local SQUID as proxy
  hosts: all
  become: true

  vars:
    required_packages:
        - bind-utils
        - net-tools
        - telnet
        - traceroute
    fedora_repos:
        - fedora.repo
        - fedora-updates.repo
        - fedora-updates-testing.repo
        - fedora-modular.repo
        - fedora-updates-modular.repo
        - fedora-updates-testing-modular.repo
    centos_repos:
        - CentOS-Linux-AppStream.repo
        - CentOS-Linux-BaseOS.repo
        - CentOS-Linux-ContinuousRelease.repo
        - CentOS-Linux-Debuginfo.repo
        - CentOS-Linux-Devel.repo
        - CentOS-Linux-Extras.repo
        - CentOS-Linux-FastTrack.repo
        - CentOS-Linux-HighAvailability.repo
        - CentOS-Linux-Media.repo
        - CentOS-Linux-Plus.repo
        - CentOS-Linux-PowerTools.repo
        - CentOS-Linux-Sources.repo
    centos_stream_repos:
        - CentOS-Stream-AppStream.repo
        - CentOS-Stream-BaseOS.repo
        - CentOS-Stream-Debuginfo.repo
        - CentOS-Stream-Extras.repo
        - CentOS-Stream-HighAvailability.repo
        - CentOS-Stream-Media.repo
        - CentOS-Stream-PowerTools.repo
        - CentOS-Stream-RealTime.repo
    proxy: "http://192.168.122.1:3128"

  tasks:
    - name: "Install required packages: {{ required_packages | join(', ') }}"
      dnf:
        name: "{{ required_packages }}"
        state: present

    - name: Set time zone
      command: "timedatectl set-timezone Europe/Vienna"

    - name: Set locale
      command: localectl set-locale en_US.UTF-8

    - name: Ignore DNS and routes from management connection
      shell: |
        nmcli connection add \
            con-name Management \
            type ethernet \
            ifname eth0 \
            ipv4.ignore-auto-dns yes \
            ipv4.ignore-auto-routes yes
        nmcli con up Management
        for con in $(
            nmcli --fields uuid,device,type,name con show |
                grep -v Management |
                awk '/ethernet/ { print $1; }'
            ) ; do
            nmcli con del $con
        done



        #nmcli connection add \
            #con-name Lab_Linux_Internal \
            #type ethernet \
            #ifname eth1

    - name: Reboot
      reboot:
