- name: Webserver
  hosts: all
  become: true

  vars:
    packages:
      - httpd
      - mod_auth_gssapi
      - mod_security
      - mod_session
      - mod_ssl

  tasks:
    - name: Install Updates
      dnf:
        name: "*"
        state: latest

    - name: Install epel
      dnf:
        name:
          - epel-release
          - epel-next-release
        state: latest

    - name: "Install packages: {{ packages | join(', ') }}"
      dnf:
        name: "{{ packages }}"
        state: latest

    - name: Start Apache
      service:
        name: htttpd
        status: started
        enabled: yes
