- name: Apply Workstation Roles
  hosts: all
  become: true

  vars:
    trusted_uris: [".linux.lab", ".test.lab"]
    delegation_uris: ["cloud.test.lab"]
    managed_bookmarks:
        - { "name": "Nextcloud", "url": "http://cloud.test.lab"}

  roles:
    - evolution
    - firefox
    - thunderbird
    - thunderbird
