- name: Apply Workstation Roles
  hosts: all
  become: true

  vars:
    trusted_uris: [".linux.lab", ".test.lab"]
    delegation_uris: ["cloud.test.lab"]
    managed_bookmarks:
        - name: "Nextcloud"
          url: "https://cloud.test.lab"
        - name: "Printserver"
          url: "https://printserver.linux.lab:631"
    skip_repo_backup: true
    commercial_packages: []
    gui_rpm_packages_fedora:
        - sddm
        - dolphin

  roles:
    - gui
    - evolution
    - firefox
    - thunderbird
    - thunderbird
